### PR TITLE
Ensure Correct Naming convention is adopted for unique event structures. 

### PR DESCRIPTION
**Pull request by danlages**
Adjusts `Main.swift` in order to ensure that events are named in line with the modern camelCase Convention. 

The result of this change can be seen in TrackingEvents.swift:

Screenshot 2021-04-27 at 20 04 44

This is a breaking change and the versioning will reflect this upon merge to the main repository.

### CODE REVIEW

**Review by Henbyr — APPROVED** [review]
LGTM

**Review by antoniostrijdom — CHANGES_REQUESTED** [review]
Worth adding a unit test for `sanitised(...)`.

**Review by antoniostrijdom — APPROVED** [review]
We can explore testing options later... this doesn't seem to be covered at all right now.

**Comment by danlages** [comment]
> We can explore testing options later... this doesn't seem to be covered at all right now.

Yep, as discussed on slack, we'll look at testing generation in more detail at a later point. Covering for this change seems out of scope.

**Pull request merged**
